import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/homepage/Header";
import Footer from "../components/homepage/Footer";

export const metadata: Metadata = {
  title: "Cyberware Glogal-Defense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <Header />
        {children}
        <Footer />

        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
      </body>
    </html>
  );
}
